# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0337663c95334aad33b294e35b6e291363646dbd3c6a33603d3fd56032571a26d7dd3a19e464b23ce60fb6aab5b14a3c9b13224b0dc437f754ac152b7b0e8865

test:
  secret_key_base: 14148b213cf36145386ebe416cebec1250d1f90da3f41973491d84c4a3de6de2a0db65890940844ce68bc061d5dee6e38c7cbccbcaf39a5efff29f5cd6ecefd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
